#ifndef __ALL_H__
#define __ALL_H__

#include "MK60F15.h"
#include "common.h"
#include "ADC.h"
#include "GPIO.h"
#include "INT.h"
#include "PIT.h"
#include "systick.h"
#include "UART.h"
#include "DAC.h"
#include "WDOG.h"
#include "I2C.h"
#include "FTM.h"
#include "DMA.h"
#include "LCD.h"
#include "MPU6050.h"
#include "MS5611.h"
#include "HMC5883.h"
#include "project.h"
#include "PID.h"
#include "SPI.h"
#include "Fuzzy.h"
#include "SCCB.h"
#include "camera_7670.h"
#include "TFT.h"
#endif